# FROM fenglc/pgadmin4
FROM dpage/pgadmin4

# user: pgadmin4@pgadmin.org
# password: admin
# pg_dump & postgresql all in  "/usr/bin"
# backup in "/var/lib/pgadmin/storage/pgadmin4"

ENV PGADMIN_LISTEN_PORT=5050
ENV PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
ENV PGADMIN_DEFAULT_PASSWORD=admin

EXPOSE 5050
